# Site settings
title: Proxy Codex
description: My Blog.
url: "aeternam.pages.dev"
baseurl: ""
usernames:
  discord: proxy133777
  github: AETERNAM-X

permalink: pretty

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - package.json
  - package-lock.json
  - optimize-css.js
  - minify.js
  - minify-js.js
  - beasties.mjs
  - node_modules/
  - Gemfile
  - Gemfile.lock

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax: false
      social: true