# Site settings
title: Proxy Codex
description: My Blog.
url: "aeternam.pages.dev"
baseurl: ""
usernames:
  discord: proxy133777
  github: AETERNAM-X

permalink: pretty

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax: false
      social: true